name: daleel_child
description: معلمي (دليل الطفل سابقًا) - منصة تعليمية عربية وإنجليزية للأطفال من الروضة حتى الصف الثالث.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5
  flutter_tts: ^4.2.5
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/data/
