import 'dart:math' as math;
import 'package:flutter/material.dart';
import '../../core/audio/voice_service.dart';
import '../../core/localization/arabic_numbers.dart';
import '../../data/content.dart';
import '../../widgets/app_feedback.dart';

class KindergartenStageScreenV3 extends StatelessWidget {
  final String stageId;
  const KindergartenStageScreenV3({super.key, required this.stageId});
  bool get kg2 => stageId == 'kg2';
  @override Widget build(BuildContext c) {
    final items = kg2 ? const [('الحروف','أولي ووسطي وآخري + نطق',Icons.abc_rounded,Color(0xFF7652FF)),('الأرقام','١ إلى ٥٠ + الآحاد والعشرات',Icons.pin_rounded,Color(0xFF18A7E8)),('الكتابة','حروف وأرقام ودمج + لون القلم',Icons.draw_rounded,Color(0xFF16B878)),('الألوان','ألوان وحيوان بنفس اللون',Icons.palette_rounded,Color(0xFFFF8A3D)),('الأشكال','أساسية ومتقدمة مع النطق',Icons.category_rounded,Color(0xFFE94F9B)),('القصص والألعاب','قصص وألعاب تعليمية',Icons.auto_stories_rounded,Color(0xFFFFB300))]: const [('الحروف','٢٨ حرفًا عربيًا + صوت واسم وكلمة',Icons.abc_rounded,Color(0xFF7652FF)),('الأرقام','من ١ إلى ١٠ مع النطق',Icons.pin_rounded,Color(0xFF18A7E8)),('الكتابة','حروف وأرقام + اختيار لون القلم',Icons.draw_rounded,Color(0xFF16B878)),('الألوان','ألوان وحيوان بنفس اللون',Icons.palette_rounded,Color(0xFFFF8A3D)),('الأشكال','مربع ومثلث ودائرة ومستطيل ومنحرف وشبه منحرف',Icons.category_rounded,Color(0xFFE94F9B)),('الألعاب','لعبة حروف ولعبة أرقام',Icons.sports_esports_rounded,Color(0xFFFFB300))];
    return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text(kg2?'الروضة الثانية':'الروضة الأولى')),body:ListView(padding:const EdgeInsets.all(16),children:[_Card('🌟',kg2?'الروضة الثانية':'الروضة الأولى','تعلم بالصوت واللون والكتابة واللعب',const [Color(0xFF7652FF),Color(0xFF18A7E8)]),const SizedBox(height:16),...items.map((x)=>Padding(padding:const EdgeInsets.only(bottom:12),child:_Card(x.$3,x.$1,x.$2,[x.$4,x.$4.withValues(alpha:.65)],()=>_open(c,x.$1))))])));
  }
  void _open(BuildContext c,String t){Widget p;switch(t){case'الحروف':p=_Letters(kg2);break;case'الأرقام':p=_Numbers(kg2);break;case'الكتابة':p=_Writing(kg2);break;case'الألوان':p=const _Colors();break;case'الأشكال':p=_Shapes(kg2);break;default:p=_Games(kg2);}Navigator.push(c,MaterialPageRoute(builder:(_)=>p));}
}
class _Card extends StatelessWidget{final dynamic a;final String title,sub;final List<Color> colors;final VoidCallback? tap;const _Card(this.a,this.title,this.sub,this.colors,[this.tap]);@override Widget build(BuildContext c)=>App3DCard(onTap:tap??()=>AppFeedback.show('🌟 $title'),encouragement:tap==null?'🌟 $title':null,child:Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(gradient:LinearGradient(colors:colors),borderRadius:BorderRadius.circular(24)),child:Row(children:[a is IconData?Icon(a as IconData,color:Colors.white,size:40):Text(a.toString(),style:const TextStyle(fontSize:42)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(color:Colors.white,fontSize:21,fontWeight:FontWeight.w900)),Text(sub,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w600))]))]));}
class _Page extends StatelessWidget{final String title;final List<Widget> children;const _Page(this.title,this.children);@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text(title)),body:ListView(padding:const EdgeInsets.all(16),children:children)));}
class _Btn extends StatelessWidget{final String t;final Color color;final VoidCallback f;const _Btn(this.t,this.color,this.f);@override Widget build(BuildContext c)=>App3DCard(onTap:f,encouragement:'✨ $t',child:Container(padding:const EdgeInsets.symmetric(vertical:14),decoration:BoxDecoration(color:color,borderRadius:BorderRadius.circular(18)),child:Center(child:Text(t,textAlign:TextAlign.center,style:const TextStyle(color:Colors.white,fontSize:17,fontWeight:FontWeight.w900)))));}
class _Letters extends StatefulWidget{final bool kg2;const _Letters(this.kg2);@override State<_Letters> createState()=>_LettersState();}
class _LettersState extends State<_Letters>{int i=0;@override Widget build(BuildContext c){final x=arabicLetters[i];final f=_forms[x.letter]??[x.letter,x.letter,x.letter];return _Page('الحروف العربية',[Text('${arNum(i+1)} من ${arNum(28)}',textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:10),App3DCard(onTap:()=>VoiceService.arabicLetterSound(x.letter,fallbackText:x.sound),encouragement:'🔊 صوت الحرف',child:Container(padding:const EdgeInsets.all(18),decoration:const BoxDecoration(gradient:LinearGradient(colors:[Color(0xFF7652FF),Color(0xFF536DFE)]),borderRadius:BorderRadius.all(Radius.circular(24))),child:Column(children:[Text(x.letter,style:const TextStyle(color:Colors.white,fontSize:105,fontWeight:FontWeight.w900)),Text('صوت القراءة: ${x.sound}',style:const TextStyle(color:Colors.white,fontSize:19)),Text('اسم الحرف: ${x.word}',style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w800))]))),if(widget.kg2)...[const SizedBox(height:10),Row(children:[for(int j=0;j<3;j++)Expanded(child:Container(margin:EdgeInsets.only(left:j==0?0:5),padding:const EdgeInsets.all(8),decoration:BoxDecoration(color:const Color(0xFF7652FF).withValues(alpha:.12),borderRadius:BorderRadius.circular(15)),child:Column(children:[Text(f[j],style:const TextStyle(fontSize:35,fontWeight:FontWeight.w900)),Text(['أولي','وسطي','آخري'][j],style:const TextStyle(fontWeight:FontWeight.w800))])))]),const SizedBox(height:12)],Row(children:[Expanded(child:_Btn('السابق',const Color(0xFFE94F9B),i>0?()=>setState(()=>i--):()=>AppFeedback.show('💛 البداية'))),const SizedBox(width:7),Expanded(child:_Btn('🔊 نطق',const Color(0xFF18A7E8),()=>VoiceService.arabicLetterSound(x.letter,fallbackText:x.sound))),const SizedBox(width:7),Expanded(child:_Btn('التالي',const Color(0xFF16B878),i<27?()=>setState(()=>i++):()=>AppFeedback.show('🏆 أكملت الحروف!')))])]);}}
const _forms={'ب':['بـ','ـبـ','ـب'],'ت':['تـ','ـتـ','ـت'],'ث':['ثـ','ـثـ','ـث'],'ج':['جـ','ـجـ','ـج'],'ح':['حـ','ـحـ','ـح'],'خ':['خـ','ـخـ','ـخ'],'س':['سـ','ـسـ','ـس'],'ش':['شـ','ـشـ','ـش'],'ص':['صـ','ـصـ','ـص'],'ض':['ضـ','ـضـ','ـض'],'ط':['طـ','ـطـ','ـط'],'ظ':['ظـ','ـظـ','ـظ'],'ع':['عـ','ـعـ','ـع'],'غ':['غـ','ـغـ','ـغ'],'ف':['فـ','ـفـ','ـف'],'ق':['قـ','ـقـ','ـق'],'ك':['كـ','ـكـ','ـك'],'ل':['لـ','ـلـ','ـل'],'م':['مـ','ـمـ','ـم'],'ن':['نـ','ـنـ','ـن'],'ه':['هـ','ـهـ','ـه'],'ي':['يـ','ـيـ','ـي']};
class _Numbers extends StatefulWidget{final bool kg2;const _Numbers(this.kg2);@override State<_Numbers> createState()=>_NumbersState();}
class _NumbersState extends State<_Numbers>{bool places=false;@override Widget build(BuildContext c){final max=widget.kg2?50:10;return places&&widget.kg2?const _Place():_Page('الأرقام',[if(widget.kg2)Row(children:[Expanded(child:_Btn('الأعداد ١–٥٠',const Color(0xFF18A7E8),()=>setState(()=>places=false))),const SizedBox(width:8),Expanded(child:_Btn('مراتب الأعداد',const Color(0xFF7652FF),()=>setState(()=>places=true)))]),const SizedBox(height:14),GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:max,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:3,crossAxisSpacing:10,mainAxisSpacing:10),itemBuilder:(_,i)=>App3DCard(onTap:()=>VoiceService.arabic(_num(i+1)),encouragement:'🔊 ${_num(i+1)}',child:Container(decoration:const BoxDecoration(gradient:LinearGradient(colors:[Color(0xFF18A7E8),Color(0xFF42A5F5)]),borderRadius:BorderRadius.all(Radius.circular(20))),child:Center(child:Text(arNum(i+1),style:const TextStyle(color:Colors.white,fontSize:38,fontWeight:FontWeight.w900))))))]);}}
class _Place extends StatefulWidget{const _Place();@override State<_Place> createState()=>_PlaceState();}
class _PlaceState extends State<_Place>{int n=24;String selected='العشرات';@override Widget build(BuildContext c){final t=n~/10,o=n%10;return _Page('مراتب الأعداد',[const Text('درس تعليمي للقيمة المكانية وليس اختبارًا',textAlign:TextAlign.center,style:TextStyle(fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:12),Text(arNum(n),textAlign:TextAlign.center,style:const TextStyle(fontSize:70,fontWeight:FontWeight.w900)),Row(children:[Expanded(child:_Btn('الآحاد: ${arNum(o)}',selected=='الآحاد'?const Color(0xFF16B878):const Color(0xFF8BCFAF),()=>setState(()=>selected='الآحاد'))),const SizedBox(width:10),Expanded(child:_Btn('العشرات: ${arNum(t)}',selected=='العشرات'?const Color(0xFF7652FF):const Color(0xFFB5A5E8),()=>setState(()=>selected='العشرات')))]),Text('الاختيار الحالي: $selected',textAlign:TextAlign.center,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),Slider(min:10,max:50,divisions:40,value:n.toDouble(),label:arNum(n),onChanged:(v)=>setState(()=>n=v.round()))]);}}
class _Writing extends StatefulWidget{final bool kg2;const _Writing(this.kg2);@override State<_Writing> createState()=>_WritingState();}
class _WritingState extends State<_Writing>{int tab=0,i=0;Color ink=const Color(0xFF7652FF);@override Widget build(BuildContext c){final letter=tab==0;final max=letter?28:(widget.kg2?50:10);final guide=letter?arabicLetters[i].letter:arNum(i+1);return _Page('الكتابة',[Row(children:[Expanded(child:_Btn('الحروف',const Color(0xFF7652FF),()=>setState(()=>tab=0))),const SizedBox(width:8),Expanded(child:_Btn('الأرقام',const Color(0xFF18A7E8),()=>setState(()=>tab=1)))]),const SizedBox(height:12),Text('اكتب: $guide',textAlign:TextAlign.center,style:const TextStyle(fontSize:25,fontWeight:FontWeight.w900)),_Board(guide,ink,(x)=>setState(()=>ink=x)),if(widget.kg2&&letter)const Padding(padding:EdgeInsets.all(8),child:Text('دمج: د+و • ن+ا • د+ي • ب+ا • م+ا • ل+ا',textAlign:TextAlign.center,style:TextStyle(fontWeight:FontWeight.w800)),if(widget.kg2&&!letter)const Padding(padding:EdgeInsets.all(8),child:Text('القيمة المكانية: الآحاد والعشرات',textAlign:TextAlign.center,style:TextStyle(fontWeight:FontWeight.w800)),Row(children:[Expanded(child:_Btn('السابق',const Color(0xFFE94F9B),i>0?()=>setState(()=>i--):()=>AppFeedback.show('💛 البداية'))),const SizedBox(width:8),Expanded(child:_Btn('🔊 اسمع',const Color(0xFF7652FF),()=>letter?VoiceService.arabicLetterSound(arabicLetters[i].letter,fallbackText:arabicLetters[i].sound):VoiceService.arabic(_num(i+1)))),const SizedBox(width:8),Expanded(child:_Btn('التالي',const Color(0xFF16B878),i<max-1?()=>setState(()=>i++):()=>AppFeedback.show('🏆 أحسنت!')))])]);}}
class _Board extends StatefulWidget{final String guide;final Color color;final ValueChanged<Color> onColor;const _Board(this.guide,this.color,this.onColor);@override State<_Board> createState()=>_BoardState();}
class _BoardState extends State<_Board>{final List<List<Offset>> strokes=[];List<Offset> current=[];@override Widget build(BuildContext c)=>Column(children:[Container(height:290,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(24),border:Border.all(color:widget.color,width:3)),child:Listener(behavior:HitTestBehavior.opaque,onPointerDown:(e)=>setState(()=>current=[e.localPosition]),onPointerMove:(e)=>setState(()=>current=[...current,e.localPosition]),onPointerUp:(_){if(current.isNotEmpty)strokes.add(List.of(current));current=[];setState((){});},onPointerCancel:(_){current=[];setState((){});},child:CustomPaint(painter:_Painter(widget.guide,widget.color,strokes,current),child:const SizedBox.expand()))),SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:[const Text('لون القلم: '),for(final x in [Colors.black,Colors.red,Colors.blue,Colors.green,Colors.orange,Colors.purple,Colors.pink])GestureDetector(onTap:()=>widget.onColor(x),child:Container(width:30,height:30,margin:const EdgeInsets.all(3),decoration:BoxDecoration(color:x,shape:BoxShape.circle))) ])),TextButton.icon(onPressed:()=>setState(strokes.clear),icon:const Icon(Icons.delete_outline),label:const Text('مسح'))]);}
class _Painter extends CustomPainter{final String guide;final Color color;final List<List<Offset>> strokes,current;_Painter(this.guide,this.color,this.strokes,this.current);@override void paint(Canvas c,Size s){final p=Paint()..color=color..strokeWidth=9..strokeCap=StrokeCap.round;void d(List<Offset>a){for(int i=1;i<a.length;i++)c.drawLine(a[i-1],a[i],p);if(a.length==1)c.drawCircle(a.first,5,p);}for(final a in strokes)d(a);d(current);final tp=TextPainter(text:TextSpan(text:guide,style:TextStyle(fontSize:170,fontWeight:FontWeight.w900,color:color.withValues(alpha:.08))),textDirection:TextDirection.rtl)..layout(maxWidth:s.width);tp.paint(c,Offset((s.width-tp.width)/2,(s.height-tp.height)/2));}@override bool shouldRepaint(covariant _Painter old)=>true;}
class _Colors extends StatelessWidget{const _Colors();@override Widget build(BuildContext c){const d=[('أبيض',Color(0xFFF5F5F5),'🕊️'),('أسود',Color(0xFF222222),'🐦'),('أحمر',Color(0xFFE53935),'🍎'),('أزرق',Color(0xFF1E88E5),'🐟'),('أخضر',Color(0xFF43A047),'🐸'),('أصفر',Color(0xFFFDD835),'🐝'),('برتقالي',Color(0xFFFB8C00),'🍊'),('بنفسجي',Color(0xFF8E24AA),'🦋'),('وردي',Color(0xFFD81B60),'🌸'),('بني',Color(0xFF795548),'🐻'),('رمادي',Color(0xFF757575),'🐘'),('سماوي',Color(0xFF00ACC1),'🐦')];return _Page('الألوان',[GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:d.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:10,mainAxisSpacing:10),itemBuilder:(_,i){final x=d[i];return App3DCard(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>_ColorDraw(x.$1,x.$2,x.$3))),encouragement:'🎨 ${x.$1}',child:Container(decoration:BoxDecoration(color:x.$2,borderRadius:BorderRadius.circular(22)),child:Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(x.$3,style:const TextStyle(fontSize:44)),Text(x.$1,style:TextStyle(color:x.$2.computeLuminance()>.55?Colors.black:Colors.white,fontSize:20,fontWeight:FontWeight.w900))])));})]);}}
class _ColorDraw extends StatefulWidget{final String name,emoji;final Color color;const _ColorDraw(this.name,this.color,this.emoji);@override State<_ColorDraw> createState()=>_ColorDrawState();}
class _ColorDrawState extends State<_ColorDraw>{final List<List<Offset>> strokes=[];List<Offset> current=[];@override Widget build(BuildContext c)=>_Page('رسم اللون',[Text('${widget.emoji} ارسم بلون ${widget.name}',textAlign:TextAlign.center,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:10),Container(height:380,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(24),border:Border.all(color:widget.color,width:4)),child:Listener(behavior:HitTestBehavior.opaque,onPointerDown:(e)=>setState(()=>current=[e.localPosition]),onPointerMove:(e)=>setState(()=>current=[...current,e.localPosition]),onPointerUp:(_){if(current.isNotEmpty)strokes.add(List.of(current));current=[];setState((){});},onPointerCancel:(_){current=[];setState((){});},child:CustomPaint(painter:_Painter(widget.emoji,widget.color,strokes,current),child:const SizedBox.expand()))),_Btn('🔊 انطق اللون',widget.color,()=>VoiceService.arabic(widget.name)),TextButton.icon(onPressed:()=>setState(strokes.clear),icon:const Icon(Icons.delete_outline),label:const Text('مسح الرسم'))]);}
class _Shapes extends StatelessWidget{final bool kg2;const _Shapes(this.kg2);@override Widget build(BuildContext c){final names=kg2?const['مربع','مثلث','دائرة','مستطيل','منحرف','شبه منحرف','خماسي','سداسي','ثماني','بيضاوي','معين','ديناري']:const['مربع','مثلث','دائرة','مستطيل','منحرف','شبه منحرف'];return _Page('الأشكال',[GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:names.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:10,mainAxisSpacing:10),itemBuilder:(_,i)=>App3DCard(onTap:()=>VoiceService.arabic(names[i]),encouragement:'🔷 ${names[i]}',child:Column(children:[Expanded(child:CustomPaint(painter:_ShapePainter(i),child:const SizedBox.expand())),Text(names[i],style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:6)]))) ]);}}
class _ShapePainter extends CustomPainter{final int type;_ShapePainter(this.type);@override void paint(Canvas c,Size s){final p=Paint()..color=Colors.primaries[type%Colors.primaries.length].withValues(alpha:.85);final cx=s.width/2,cy=s.height/2,r=s.shortestSide*.28;if(type==0){c.drawRect(Rect.fromCenter(center:Offset(cx,cy),width:r*1.7,height:r*1.7),p);return;}if(type==2){c.drawCircle(Offset(cx,cy),r,p);return;}final sides=type==1?3:type==3?4:type==4||type==5?4:type==6?5:type==7?6:type==8?8:type==9?0:4;if(type==9){c.drawOval(Rect.fromCenter(center:Offset(cx,cy),width:r*2.2,height:r*1.35),p);return;}final path=Path();for(int i=0;i<sides;i++){final a=-math.pi/2+i*2*math.pi/sides;final rx=type==4||type==5?(i==0||i==1?r*1.15:r*.85):r;final q=Offset(cx+rx*math.cos(a),cy+rx*math.sin(a));if(i==0)path.moveTo(q.dx,q.dy);else path.lineTo(q.dx,q.dy);}path.close();c.drawPath(path,p);}@override bool shouldRepaint(covariant _ShapePainter old)=>old.type!=type;}
class _Games extends StatelessWidget{final bool kg2;const _Games(this.kg2);@override Widget build(BuildContext c)=>_Page(kg2?'القصص والألعاب':'الألعاب',[for(final x in kg2?['القصة الأولى','القصة الثانية','لعبة الحروف','لعبة دمج حرفين','لعبة الآحاد','لعبة العشرات']:['لعبة الحروف','لعبة الأرقام'])_Card('⭐',x,'نشاط مع تأثيرات وتشجيع',[const Color(0xFF7652FF),const Color(0xFFE94F9B)],()=>AppFeedback.show('🎉 أحسنت!'))]);}
String _num(int n){const a=['','واحد','اثنان','ثلاثة','أربعة','خمسة','ستة','سبعة','ثمانية','تسعة','عشرة'];if(n<=10)return a[n];if(n<20)return n==11?'أحد عشر':n==12?'اثنا عشر':'${a[n-10]} عشر';const t=['','','عشرون','ثلاثون','أربعون','خمسون'];final o=n%10;return o==0?t[n~/10]:'${a[o]} و${t[n~/10]}';}
