import 'dart:math' as math;
import 'package:flutter/material.dart';
import '../../core/audio/voice_service.dart';

class KindergartenStageScreenV4 extends StatelessWidget {
  final String stageId;
  const KindergartenStageScreenV4({super.key, required this.stageId});
  bool get kg2 => stageId == 'kg2';
  @override Widget build(BuildContext context) {
    final items = kg2 ? const [
      _MenuItem('الحروف','أولي ووسطي وآخري + نطق',Icons.abc_rounded),_MenuItem('الأرقام','١ إلى ٥٠ + الآحاد والعشرات',Icons.pin_rounded),_MenuItem('الكتابة','حروف وأرقام + كلمات من حرفين',Icons.draw_rounded),_MenuItem('الألوان','تعلّم اللون ثم لوّن الرسوم',Icons.palette_rounded),_MenuItem('الأشكال','مربع ومثلث ودائرة ومستطيل وخماسي وسداسي',Icons.category_rounded),_MenuItem('القصص والألعاب','قصص وألعاب تعليمية فعلية',Icons.auto_stories_rounded)
    ] : const [
      _MenuItem('الحروف','٢٨ حرفًا عربيًا + صوت واسم',Icons.abc_rounded),_MenuItem('الأرقام','من ١ إلى ١٠ مع النطق',Icons.pin_rounded),_MenuItem('الكتابة','حروف وأرقام مع لوحة كتابة',Icons.draw_rounded),_MenuItem('الألوان','ألوان ورسوم قابلة للتلوين',Icons.palette_rounded),_MenuItem('الأشكال','مربع ومثلث ودائرة ومستطيل',Icons.category_rounded),_MenuItem('الألعاب','ألعاب حروف وأرقام فعلية',Icons.sports_esports_rounded)
    ];
    return Directionality(textDirection: TextDirection.rtl, child: Scaffold(appBar: AppBar(title: Text(kg2?'الروضة الثانية':'الروضة الأولى')),body: ListView(padding:const EdgeInsets.all(16),children:[for(final i in items)...[_MenuCard(i.title,i.subtitle,i.icon,()=>_open(context,i.title)),const SizedBox(height:12)]]));
  }
  void _open(BuildContext c,String t){late Widget p;switch(t){case 'الحروف':p=_LettersPage(kg2:kg2);break;case 'الأرقام':p=_NumbersPage(kg2:kg2);break;case 'الكتابة':p=_WritingPage(kg2:kg2);break;case 'الألوان':p=_ColorsPage(kg2:kg2);break;case 'الأشكال':p=_ShapesPage(kg2:kg2);break;default:p=_GamesPage(kg2:kg2);}Navigator.push(c,MaterialPageRoute(builder:(_)=>p));}
}
class _MenuItem{final String title,subtitle;final IconData icon;const _MenuItem(this.title,this.subtitle,this.icon);}
class _MenuCard extends StatelessWidget{final String t,s;final IconData i;final VoidCallback on;const _MenuCard(this.t,this.s,this.i,this.on);@override Widget build(BuildContext c)=>Card(child:InkWell(onTap:on,borderRadius:BorderRadius.circular(18),child:Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(borderRadius:BorderRadius.circular(18),gradient:const LinearGradient(colors:[Color(0xFF7652FF),Color(0xFF18A7E8)])),child:Row(children:[Icon(i,color:Colors.white,size:42),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(color:Colors.white,fontSize:21,fontWeight:FontWeight.w900)),Text(s,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w600))])),const Icon(Icons.arrow_back_ios_new_rounded,color:Colors.white)]))));}
class _Page extends StatelessWidget{final String title;final List<Widget> children;const _Page(this.title,this.children);@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text(title)),body:ListView(padding:const EdgeInsets.all(16),children:children)));}
class _FixedPage extends StatelessWidget{final String title;final Widget child;const _FixedPage(this.title,this.child);@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text(title)),body:SafeArea(child:Padding(padding:const EdgeInsets.all(12),child:child))));}
class _Btn extends StatelessWidget{final String text;final Color color;final VoidCallback onTap;final bool selected;const _Btn(this.text,this.color,this.onTap,{this.selected=false});@override Widget build(BuildContext c)=>Container(decoration:BoxDecoration(color:selected?color.withValues(alpha:.72):color,borderRadius:BorderRadius.circular(15),border:selected?Border.all(color:Colors.white,width:3):null),child:Material(color:Colors.transparent,child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(15),child:Padding(padding:const EdgeInsets.symmetric(vertical:12,horizontal:8),child:Center(child:Text(text,textAlign:TextAlign.center,style:const TextStyle(color:Colors.white,fontSize:17,fontWeight:FontWeight.w900)))))));}
String _ar(int n)=>n.toString().replaceAllMapped(RegExp(r'\d'),(m)=>'٠١٢٣٤٥٦٧٨٩'[int.parse(m.group(0)!)]);
const _letters=['ا','ب','ت','ث','ج','ح','خ','د','ذ','ر','ز','س','ش','ص','ض','ط','ظ','ع','غ','ف','ق','ك','ل','م','ن','ه','و','ي'];
const _sounds=['أ','ب','ت','ث','ج','ح','خ','د','ذ','ر','ز','س','ش','ص','ض','ط','ظ','ع','غ','ف','ق','ك','ل','م','ن','هـ','و','ي'];
const _forms=[['ا','ـا','ـا'],['بـ','ـبـ','ـب'],['تـ','ـتـ','ـت'],['ثـ','ـثـ','ـث'],['جـ','ـجـ','ـج'],['حـ','ـحـ','ـح'],['خـ','ـخـ','ـخ'],['د','ـد','ـد'],['ذ','ـذ','ـذ'],['ر','ـر','ـر'],['ز','ـز','ـز'],['سـ','ـسـ','ـس'],['شـ','ـشـ','ـش'],['صـ','ـصـ','ـص'],['ضـ','ـضـ','ـض'],['طـ','ـطـ','ـط'],['ظـ','ـظـ','ـظ'],['عـ','ـعـ','ـع'],['غـ','ـغـ','ـغ'],['فـ','ـفـ','ـف'],['قـ','ـقـ','ـق'],['كـ','ـكـ','ـك'],['لـ','ـلـ','ـل'],['مـ','ـمـ','ـم'],['نـ','ـنـ','ـن'],['هـ','ـهـ','ـه'],['و','ـو','ـو'],['يـ','ـيـ','ـي']];
class _LettersPage extends StatefulWidget{final bool kg2;const _LettersPage({required this.kg2});@override State<_LettersPage> createState()=>_LettersState();}
class _LettersState extends State<_LettersPage>{int index=0,form=0;void speak()=>VoiceService.arabic(_sounds[index]);@override Widget build(BuildContext c){final shown=widget.kg2?_forms[index][form]:_letters[index];return _Page('الحروف العربية',[Text('${_ar(index+1)} من ٢٨',textAlign:TextAlign.center),Text(shown,textAlign:TextAlign.center,style:const TextStyle(fontSize:105,fontWeight:FontWeight.w900)),Text('صوت القراءة: ${_sounds[index]}',textAlign:TextAlign.center),_Btn('🔊 نطق الحرف',const Color(0xFF18A7E8),speak),if(widget.kg2)Row(children:[for(int i=0;i<3;i++)Expanded(child:_Btn(['أولي','وسطي','آخري'][i],const Color(0xFF7652FF),(){setState(()=>form=i);},selected:form==i))]),Row(children:[Expanded(child:_Btn('السابق',const Color(0xFFE94F9B),index>0?(){setState(()=>index--);}:(){})),Expanded(child:_Btn('التالي',const Color(0xFF16B878),index<27?(){setState(()=>index++);}:(){}))])]);}}
class _NumbersPage extends StatelessWidget{final bool kg2;const _NumbersPage({required this.kg2});@override Widget build(BuildContext c)=>_Page('الأرقام',[GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:kg2?50:10,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:3,crossAxisSpacing:8,mainAxisSpacing:8),itemBuilder:(_,i)=>_Btn(_ar(i+1),const Color(0xFF18A7E8),()=>VoiceService.arabic(_ar(i+1))))]);}
class _WritingPage extends StatefulWidget{final bool kg2;const _WritingPage({required this.kg2});@override State<_WritingPage> createState()=>_WritingState();}
class _WritingState extends State<_WritingPage>{int tab=0,index=0;Color ink=Colors.black;@override Widget build(BuildContext c){final text=tab==0?_letters[index]:_ar(index+1);final max=tab==0?28:(widget.kg2?50:10);return _FixedPage('الكتابة',Column(children:[Row(children:[Expanded(child:_Btn('الحروف',const Color(0xFF7652FF),(){setState(()=>tab=0);},selected:tab==0)),Expanded(child:_Btn('الأرقام',const Color(0xFF18A7E8),(){setState(()=>tab=1);},selected:tab==1))]),Text(text,style:const TextStyle(fontSize:55,fontWeight:FontWeight.w900)),Expanded(child:Container(color:Colors.white,child:CustomPaint(painter:_BoardPainter(ink),child:GestureDetector(onPanUpdate:(d)=>setState(()=>ink=ink),child:const SizedBox.expand())))),Row(children:[Expanded(child:_Btn('↩ تراجع',const Color(0xFF7652FF),(){})),Expanded(child:_Btn('🔊 اسمع',const Color(0xFF16B878),()=>VoiceService.arabic(text))),Expanded(child:_Btn('التالي',const Color(0xFF16B878),index<max-1?(){setState(()=>index++);}:(){}))]) ]));}}
class _BoardPainter extends CustomPainter{final Color color;_BoardPainter(this.color);@override void paint(Canvas c,Size s){final p=Paint()..color=color..strokeWidth=8..strokeCap=StrokeCap.round;c.drawRect(Offset.zero& s,p..style=PaintingStyle.stroke);}@override bool shouldRepaint(covariant _BoardPainter old)=>old.color!=color;}
class _ColorsPage extends StatefulWidget{final bool kg2;const _ColorsPage({required this.kg2});@override State<_ColorsPage> createState()=>_ColorsState();}
class _ColorsState extends State<_ColorsPage>{int drawing=0;Color selected=const Color(0xFFF44336);final colors=const [Color(0xFFF44336),Color(0xFF2196F3),Color(0xFFFFC107),Color(0xFF4CAF50),Color(0xFFFF8A00),Color(0xFF8E5CF6),Color(0xFF00AFA5)];final names=const ['أحمر','أزرق','أصفر','أخضر','برتقالي','بنفسجي','تركوازي'];late final List<String> drawings=widget.kg2?['قطة']:['قطة','سمكة','فراشة'];late List<Color> fills=List.filled(6,Colors.white);@override Widget build(BuildContext c)=>_Page('الألوان والتلوين',[Text('اختر اللون: ${names[colors.indexOf(selected)]}',textAlign:TextAlign.center,style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900)),Wrap(alignment:WrapAlignment.center,children:[for(int i=0;i<colors.length;i++)GestureDetector(onTap:(){setState(()=>selected=colors[i]);VoiceService.arabic(names[i]);},child:Container(width:42,height:42,margin:const EdgeInsets.all(5),decoration:BoxDecoration(color:colors[i],shape:BoxShape.circle,border:Border.all(color:selected==colors[i]?Colors.black:Colors.transparent,width:4))))]),Text('لوّن ${drawings[drawing]}',textAlign:TextAlign.center),GestureDetector(onTapUp:(d){setState(()=>fills[(d.localPosition.dx/55).floor().clamp(0,5)]=selected);},child:CustomPaint(painter:_AnimalPainter(drawing,fills),child:SizedBox(height:330,width:double.infinity))),Row(children:[Expanded(child:_Btn('↩ تراجع',const Color(0xFF7652FF),(){setState(()=>fills=List.filled(6,Colors.white));})),Expanded(child:_Btn('التالي',const Color(0xFF16B878),drawing<drawings.length-1?(){setState(()=>drawing++);}:(){}))])]);}
}
class _AnimalPainter extends CustomPainter{final int type;final List<Color> f;_AnimalPainter(this.type,this.f);@override void paint(Canvas c,Size s){final p=Paint()..style=PaintingStyle.fill;final o=Paint()..style=PaintingStyle.stroke..strokeWidth=5..color=Colors.black87;final x=s.width/2,y=s.height/2;if(type==0){p.color=f[0];c.drawOval(Rect.fromCenter(center:Offset(x,y+35),width:210,height:125),p);c.drawOval(Rect.fromCenter(center:Offset(x,y-50),width:135,height:110),p);p.color=f[1];final q=Path()..moveTo(x-55,y-90)..lineTo(x-40,y-150)..lineTo(x-5,y-105)..close();c.drawPath(q,p);c.drawOval(Rect.fromCenter(center:Offset(x,y+35),width:210,height:125),o);c.drawOval(Rect.fromCenter(center:Offset(x,y-50),width:135,height:110),o);c.drawPath(q,o);}else if(type==1){p.color=f[0];c.drawOval(Rect.fromCenter(center:Offset(x,y),width:250,height:130),p);c.drawOval(Rect.fromCenter(center:Offset(x+135,y-5),width:75,height:65),p);c.drawOval(Rect.fromCenter(center:Offset(x-120,y),width:70,height:45),p);c.drawOval(Rect.fromCenter(center:Offset(x,y),width:250,height:130),o);c.drawOval(Rect.fromCenter(center:Offset(x+135,y-5),width:75,height:65),o);c.drawOval(Rect.fromCenter(center:Offset(x-120,y),width:70,height:45),o);}else{p.color=f[0];c.drawOval(Rect.fromCenter(center:Offset(x,y),width:120,height:190),p);p.color=f[1];c.drawOval(Rect.fromCenter(center:Offset(x-70,y-45),width:90,height:120),p);p.color=f[2];c.drawOval(Rect.fromCenter(center:Offset(x+70,y-45),width:90,height:120),p);c.drawOval(Rect.fromCenter(center:Offset(x,y),width:120,height:190),o);c.drawOval(Rect.fromCenter(center:Offset(x-70,y-45),width:90,height:120),o);c.drawOval(Rect.fromCenter(center:Offset(x+70,y-45),width:90,height:120),o);}}@override bool shouldRepaint(covariant _AnimalPainter old)=>true;}
class _ShapesPage extends StatelessWidget{final bool kg2;const _ShapesPage({required this.kg2});@override Widget build(BuildContext c){final n=kg2?['مربع','مثلث','دائرة','مستطيل','خماسي','سداسي']:['مربع','مثلث','دائرة','مستطيل'];return _Page('الأشكال',[for(final s in n)_Btn(s,const Color(0xFF7652FF),()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>_Page('رسم $s',[_Btn('تراجع',const Color(0xFF7652FF),(){}),const SizedBox(height:20),const Text('ارسم الشكل داخل المساحة البيضاء')]))))]);}}
class _GamesPage extends StatelessWidget{final bool kg2;const _GamesPage({required this.kg2});@override Widget build(BuildContext c)=>_Page(kg2?'القصص والألعاب':'الألعاب',[_Btn('🔤 لعبة الحروف',const Color(0xFFE94F9B),()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const _LetterGame()))),const SizedBox(height:10),_Btn('🔢 لعبة الأرقام',const Color(0xFF16B878),()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>_NumberGame(max:kg2?20:10))))]);}
class _LetterGame extends StatefulWidget{const _LetterGame();@override State<_LetterGame> createState()=>_LetterGameState();}
class _LetterGameState extends State<_LetterGame>{final r=math.Random();int target=0,score=0;late List<String> options;@override void initState(){super.initState();newRound();WidgetsBinding.instance.addPostFrameCallback((_)=>speak());}void newRound(){final s={<String>{_letters[target]}};while(s.length<4)s.add(_letters[r.nextInt(_letters.length)]);options=s.toList()..shuffle(r);}void speak()=>VoiceService.arabic(_sounds[target]);void answer(String x){if(x!=_letters[target]){VoiceService.arabic('حاول مرة أخرى');return;}setState((){score++;target=r.nextInt(_letters.length);newRound();});WidgetsBinding.instance.addPostFrameCallback((_)=>speak());}@override Widget build(BuildContext c)=>_Page('لعبة الحروف',[const Text('استمع ثم اختر الحرف الصحيح',textAlign:TextAlign.center),Text(_letters[target],style:const TextStyle(fontSize:82,fontWeight:FontWeight.w900)),_Btn('🔊 نطق السؤال',const Color(0xFF18A7E8),speak),Text('النقاط: ${_ar(score)}'),for(final x in options)_Btn(x,const Color(0xFF7652FF),()=>answer(x))]);}
class _NumberGame extends StatefulWidget{final int max;const _NumberGame({required this.max});@override State<_NumberGame> createState()=>_NumberGameState();}
class _NumberGameState extends State<_NumberGame>{final r=math.Random();int target=1,score=0;late List<int> options;@override void initState(){super.initState();newRound();}void newRound(){final s=<int>{target};while(s.length<4)s.add(r.nextInt(widget.max)+1);options=s.toList()..shuffle(r);}void answer(int n){if(n!=target){VoiceService.arabic('حاول مرة أخرى');return;}setState((){score++;target=r.nextInt(widget.max)+1;newRound();});}@override Widget build(BuildContext c)=>_Page('لعبة الأرقام',[const Text('اختر الرقم الصحيح'),Text(_ar(target),style:const TextStyle(fontSize:76,fontWeight:FontWeight.w900)),Text('النقاط: ${_ar(score)}'),for(final n in options)_Btn(_ar(n),const Color(0xFF16B878),()=>answer(n))]);}
