import 'package:flutter/material.dart';
import '../../widgets/app_feedback.dart';
import '../arabic/arabic_curriculum_screen_v16.dart';
import '../arabic/arabic_grammar_screen_v12.dart';
import '../english/english_home_screen.dart';
import '../math/math_curriculum_screen_v15.dart';
import '../math/multiplication_screen_v13.dart';
import '../writing/writing_screen.dart';
import '../children/kindergarten_stage_screen_v3.dart';
import '../games/games_screen_v11.dart';

class StageScreen extends StatelessWidget {
  final String stageId;
  const StageScreen({super.key, required this.stageId});
  @override Widget build(BuildContext context) {
    if (stageId == 'kg1' || stageId == 'kg2') return KindergartenStageScreenV3(stageId: stageId);
    if (stageId == 'prep') return const KindergartenTestsScreen();
    final grade = stageId == 'g2' ? 2 : stageId == 'g3' ? 3 : 1;
    final title = stageId == 'g2' ? 'الصف الثاني' : stageId == 'g3' ? 'الصف الثالث' : 'الصف الأول';
    final cards = <Widget>[
      _StageButton('العربية','منهج العربية المناسب للمرحلة',Icons.menu_book_rounded,const Color(0xFF7652FF),ArabicCurriculumScreenV16(grade:grade),'📚 خطوة جديدة في القراءة!'),
      if (grade >= 2) _StageButton('قواعد اللغة العربية','القواعد والتراكيب',Icons.spellcheck_rounded,const Color(0xFFE94F9B),const ArabicGrammarScreenV12(),'📝 هيا نكتشف قواعد العربية!'),
      _StageButton('الرياضيات','جمع وطرح وقيمة مكانية ومهارات أخرى',Icons.calculate_rounded,const Color(0xFF18A7E8),MathCurriculumScreenV15(grade:grade),'🧮 عقل رياضي رائع!'),
      _StageButton('جدول الضرب','حسب المرحلة',Icons.close_rounded,const Color(0xFF16B878),const MultiplicationScreenV13(),'✖️ لنصبح أبطال جدول الضرب!'),
      _StageButton('الإنجليزية','قراءة وكتابة وتعلم تدريجي',Icons.language_rounded,const Color(0xFFFF8A3D),EnglishHomeScreen(stageId:stageId),'🇬🇧 Great!'),
      _StageButton('الكتابة','كلمات وجمل وتدريب كتابي',Icons.edit_note_rounded,const Color(0xFF8E5CF6),WritingScreen(stageId:stageId),'✍️ اكتب بنفسك!'),
      _StageButton('الألعاب والقصص','نشاطات وتحديات مرتبطة بالتعلم',Icons.sports_esports_rounded,const Color(0xFFFFB300),const GamesScreenV11(),'🏆 تحدٍ جديد!'),
    ];
    return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text(title)),body:ListView(padding:const EdgeInsets.all(16),children:[App3DCard(onTap:()=>AppFeedback.show('🌟 $title — أنت تستطيع!'),child:Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:LinearGradient(colors:[Theme.of(context).colorScheme.primaryContainer,Theme.of(context).colorScheme.tertiaryContainer]),borderRadius:BorderRadius.circular(24)),child:Text(title,style:const TextStyle(fontSize:26,fontWeight:FontWeight.w900)))),const SizedBox(height:18),...cards])));
  }
}
class _StageButton extends StatelessWidget { final String title,subtitle,message; final IconData icon; final Color color; final Widget page; const _StageButton(this.title,this.subtitle,this.icon,this.color,this.page,this.message); @override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.only(bottom:12),child:App3DCard(onTap:(){AppFeedback.show(message);Navigator.push(context,MaterialPageRoute(builder:(_)=>page));},encouragement:message,child:Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(gradient:LinearGradient(colors:[color,color.withValues(alpha:.68)]),borderRadius:BorderRadius.circular(22)),child:Row(children:[Icon(icon,color:Colors.white,size:40),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.w900)),Text(subtitle,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w600))])),const Icon(Icons.arrow_back_ios_new_rounded,color:Colors.white)])))); }

class KindergartenTestsScreen extends StatelessWidget { const KindergartenTestsScreen({super.key}); @override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('اختبارات الروضة')),body:ListView(padding:const EdgeInsets.all(16),children:[App3DCard(onTap:()=>AppFeedback.show('🏆 هيا نراجع ما تعلمناه!'),child:Container(padding:const EdgeInsets.all(22),decoration:const BoxDecoration(gradient:LinearGradient(colors:[Color(0xFF8E5CF6),Color(0xFF18A7E8),Color(0xFFE94F9B)]),borderRadius:BorderRadius.all(Radius.circular(26))),child:const Text('🏆 اختبارات الروضة\nمراجعة ممتعة للروضة الأولى والثانية',style:TextStyle(color:Colors.white,fontSize:24,fontWeight:FontWeight.w900)))),const SizedBox(height:18),_TestButton('اختبار الحروف ودمج حرفين','الحروف العربية + دمج حرفين',Icons.abc_rounded,const[Color(0xFF8E5CF6),Color(0xFFE94F9B)],const _PrepLetterTest()),_TestButton('اختبار الأرقام','١ إلى ٥٠ + الآحاد والعشرات',Icons.pin_rounded,const[Color(0xFF18A7E8),Color(0xFF16B878)],const _PrepNumberTest()),_TestButton('اختبار الأشكال','تمييز الأشكال',Icons.category_rounded,const[Color(0xFFFF8A3D),Color(0xFFE94F9B)],const _PrepShapeTest()),_TestButton('اختبار الألوان','التعرف على اللون واسمه',Icons.palette_rounded,const[Color(0xFFFFC107),Color(0xFFFF8A3D)],const _PrepColorTest())])); }
}
class _TestButton extends StatelessWidget { final String title,subtitle; final IconData icon; final List<Color> colors; final Widget page; const _TestButton(this.title,this.subtitle,this.icon,this.colors,this.page); @override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.only(bottom:12),child:App3DCard(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>page)),encouragement:'✨ هيا نبدأ!',child:Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(gradient:LinearGradient(colors:colors),borderRadius:BorderRadius.circular(22)),child:Row(children:[Icon(icon,color:Colors.white,size:40),const SizedBox(width:12),Expanded(child:Text('$title\n$subtitle',style:const TextStyle(color:Colors.white,fontSize:19,fontWeight:FontWeight.w900))),const Icon(Icons.arrow_back_ios_new_rounded,color:Colors.white)])))); }
class _PrepLetterTest extends StatefulWidget{const _PrepLetterTest();@override State<_PrepLetterTest> createState()=>_PrepLetterTestState();}
class _PrepLetterTestState extends State<_PrepLetterTest>{int i=0;final qs=const[('اختر الحرف: ب',['أ','ب','ت'],'ب'),('اختر الحرف: م',['ن','م','ل'],'م'),('ما نتيجة د + و؟',['دو','دا','دي'],'دو'),('ما نتيجة ن + ا؟',['نا','نو','ني'],'نا'),('ما نتيجة ب + ا؟',['با','بو','بي'],'با')];@override Widget build(BuildContext c){final q=qs[i%qs.length];return _QuestionPage('اختبار الحروف',q.$1,q.$2,q.$3,()=>setState(()=>i++));}}
class _PrepNumberTest extends StatefulWidget{const _PrepNumberTest();@override State<_PrepNumberTest> createState()=>_PrepNumberTestState();}
class _PrepNumberTestState extends State<_PrepNumberTest>{int i=1;@override Widget build(BuildContext c){final t=i~/10,o=i%10;final choices=i<10?['$i','${i==9?1:i+1}','${i==1?3:i-1}']:['الآحاد: $o','العشرات: $t','العدد كاملًا'];final correct=i<10?'$i':(o>0?'الآحاد: $o':'العشرات: $t');return _QuestionPage('اختبار الأرقام',i<10?'اختر الرقم $i':'في العدد $i اختر قيمة الآحاد أو العشرات',choices,correct,()=>setState(()=>i=i==50?1:i+1));}}
class _PrepShapeTest extends StatefulWidget{const _PrepShapeTest();@override State<_PrepShapeTest> createState()=>_PrepShapeTestState();}
class _PrepShapeTestState extends State<_PrepShapeTest>{int i=0;final qs=[('أين المربع؟',['مربع','دائرة','مثلث'],'مربع'),('أين المثلث؟',['مستطيل','مثلث','دائرة'],'مثلث'),('أين الدائرة؟',['دائرة','مربع','منحرف'],'دائرة'),('أين المستطيل؟',['مثلث','مستطيل','مربع'],'مستطيل'),('أين المنحرف؟',['شبه منحرف','منحرف','دائرة'],'منحرف'),('أين شبه المنحرف؟',['مثلث','مربع','شبه منحرف'],'شبه منحرف'),('أين الخماسي؟',['سداسي','خماسي','دائرة'],'خماسي'),('أين السداسي؟',['سداسي','مثلث','مستطيل'],'سداسي')];@override Widget build(BuildContext c){final q=qs[i%qs.length];return _QuestionPage('اختبار الأشكال',q.$1,q.$2,q.$3,()=>setState(()=>i++));}}
class _PrepColorTest extends StatefulWidget{const _PrepColorTest();@override State<_PrepColorTest> createState()=>_PrepColorTestState();}
class _PrepColorTestState extends State<_PrepColorTest>{int i=0;final qs=[('اختر اللون الأحمر',['أحمر','أزرق','أخضر'],'أحمر'),('اختر اللون الأخضر',['أصفر','أخضر','بنفسجي'],'أخضر'),('اختر اللون الأزرق',['أزرق','وردي','برتقالي'],'أزرق'),('اختر اللون الأبيض',['أسود','أبيض','بني'],'أبيض'),('اختر اللون البنفسجي',['بنفسجي','تركوازي','رمادي'],'بنفسجي')];@override Widget build(BuildContext c){final q=qs[i%qs.length];return _QuestionPage('اختبار الألوان',q.$1,q.$2,q.$3,()=>setState(()=>i++));}}
class _QuestionPage extends StatelessWidget{final String title,question,correct;final List<String> choices;final VoidCallback onNext;const _QuestionPage(this.title,this.question,this.choices,this.correct,this.onNext);@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:Text(title)),body:ListView(padding:const EdgeInsets.all(18),children:[App3DCard(onTap:(){},child:Container(padding:const EdgeInsets.all(22),decoration:const BoxDecoration(gradient:LinearGradient(colors:[Color(0xFF8E5CF6),Color(0xFF18A7E8)]),borderRadius:BorderRadius.all(Radius.circular(24))),child:Text(question,textAlign:TextAlign.center,style:const TextStyle(color:Colors.white,fontSize:24,fontWeight:FontWeight.w900))),const SizedBox(height:18),for(final choice in choices)Padding(padding:const EdgeInsets.only(bottom:10),child:App3DCard(onTap:(){if(choice==correct){AppFeedback.show('🎉 أحسنت! إجابة صحيحة');onNext();}else{AppFeedback.show('💛 حاول مرة أخرى!');}},child:Container(padding:const EdgeInsets.symmetric(vertical:16),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF16B878),Color(0xFF18A7E8)]),borderRadius:BorderRadius.circular(18)),child:Center(child:Text(choice,style:const TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.w900))))))])));}}
